# ==========================
# SigridHQ Configuration - Sigrid Discord Server
# ==========================

# --------------------------
# Status Messages
# --------------------------
# Status messages to rotate through for the bot's presence.

statuses:
  - "Strangers 🤝"
  - "Don't Kill My Vibe ✋"
  - "Sucker Punch 🥊"
  - "Plot Twist 📚"
  - "Mirror 🪞"
  - "Don't Feel Like Crying 😢"
  - "High Five 🙌"
  - "Burning Bridges 🔥"
  - "It Gets Dark 🌑"
  - "Bad Life 💔"
  - "Head on Fire 🔥🧠"
  - "Sight of You 👀"
  - "Dynamite 💣"
  - "Basic ⚪"
  - "Home to You 🏠"
  - "Maybe It's a Good Thing ✅"
  - "Raw 🎤"
  - "Level Up ⬆️"
  - "Schedules 🗓️"
  - "Focus 🎯"
  - "Dance for Me 💃"
  - "In Vain 🌀"
  - "A Driver Saved My Night 🚗"
  - "Ring 💍"

# --------------------------
# Channel and Role IDs
# --------------------------
# IDs of channels and roles used by the bot for various functions.

liveshows_channel_id: 1159498591451222076             # Forum channel for live shows threads.
welcome_channel_id: 948283107474280449        # Channel where welcome messages are posted.
new_member_channel_id: 1052940830169628752        # Channel where new members are directed.
dm_forward_channel_id: 1403859090987286630    # Channel for forwarding direct messages.
instagram_announce_channel_id: 946013231208611880  # Discord channel ID for announcements.
instagram_ping_role_id: 1052632504668012584 # The role to ping when there's a new post.

# --------------------------
# Feature Toggles
# --------------------------
# Enable or disable specific features. Set to 'true' to enable the feature.
welcome_enabled: true     # Set to true to enable welcome messages.

# --------------------------
# Instagram Settings
# --------------------------
instagram_username: thisissigrid
instagram_poll_interval: 300   # seconds between checks.
